### ISSUE TITLE
Bionet icon

### ISSUE THREAD

**Issue by eyesmo** [EndyLab/bionet-synthesis#10]
My cursor indicates the bionet icon in the top right corner is a hyperlink/is clickable, but nothing happens when I click it, and right clicking indicates that it's just an image.
<img width="459" alt="bionetbug" src="https://user-images.githubusercontent.com/2289040/37684906-8eddfbae-2c5f-11e8-9151-3913c7200153.png">
<img width="491" alt="screen shot 2018-03-20 at 4 55 24 pm" src="https://user-images.githubusercontent.com/2289040/37684931-aa788636-2c5f-11e8-9a65-e1f888630e3a.png">

**Comment by Juul** [comment]
Hey thanks for the bug report! I've fixed it in the code but not yet deployed to endylab. Could you open new issues on the [bionet-new](https://github.com/biobricks/bionet-new/issues) repository rather than the bionet-synthesis repository?
